-- SYS 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 사용자 계정 생성
CREATE USER project1_hjh IDENTIFIED BY hjh1234;

-- 생성한 사용자 계정에 권한 부여
GRANT RESOURCE, CONNECT TO project1_hjh;

-- 테이블 스페이스 할당
ALTER USER project1_hjh DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;

-----------------------------------------

-- project1_hjh 계정
-- 회원 정보 테이블 생성
-- (회원번호)/아이디/비밀번호/이름/전화번호/주소/가입날짜(SYSDATE)/(탈퇴여부(N))

CREATE TABLE TB_USER(
	USER_NO NUMBER CONSTRAINT USER_NO_PK PRIMARY KEY,
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30),
	USER_PHONE VARCHAR2(30),
	USER_ADDR VARCHAR2(70) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y', 'N')),
	CONSTRAINT USER_ID_NAME_PHONE_U UNIQUE(USER_ID, USER_NAME, USER_PHONE)
);

SELECT * FROM TB_USER;

COMMENT ON COLUMN TB_USER.USER_NO IS '회원 번호';
COMMENT ON COLUMN TB_USER.USER_ID IS '회원 아이디';
COMMENT ON COLUMN TB_USER.USER_PW IS '회원 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN TB_USER.USER_PHONE IS '회원 전화번호';
COMMENT ON COLUMN TB_USER.USER_ADDR IS '회원 주소';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '회원 가입 날짜';
COMMENT ON COLUMN TB_USER.SECESSION_FL IS '회원 탈퇴 여부';

-- SEQUENCE
CREATE SEQUENCE SEQ_USER_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 샘플 회원 INSERT 
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'asdf01', 'asdf01', '가나다', '010-1234-5678', 
	'서울시 중구 남대문로 120 대일빌딩 2층', DEFAULT, DEFAULT);

INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'aespa0', 'aespa1', '가리나', '010-1212-2323', 
	'서울시 중구 을지로 281', TO_DATE('2020-11-17 10:30:12', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'ive01', 'ive02', '장원일', '010-2112-1212', 
	'서울시 강남구 삼성로146길 4-5', TO_DATE('2021-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'ive03', 'ive04', '안무진', '010-1201-1111', 
	'서울시 강남구 삼성로146길 4-5', TO_DATE('2021-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'itzy01', 'itzy02', '황예지', '010-0212-0212', 
	'서울시 강동구 강동대로 205', TO_DATE('2019-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'itzy03', 'itzy04', '신유진', '010-1111-0212', 
	'서울시 강동구 강동대로 205', TO_DATE('2019-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'hunt01', 'hunt02', '김정재', '010-3333-1234', 
	'서울시 강남구 도산대로 430, 202호', TO_DATE('2022-08-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'hunt03', 'hunt04', '정좌성', '010-5678-9999', 
	'서울시 강남구 도산대로 430, 202호', TO_DATE('2022-08-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'omygirl', 'mimi0', '김미혜', '010-8989-9955', 
	'서울시 마포구 망원동 373-6', DEFAULT, DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'yena3', 'yena33', '최예나', '010-5999-5959', 
	'서울시 강남구 논현로 403', TO_DATE('2018-08-31 02:00:00', 'YYYY-MM-DD HH24:MI:SS'), DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'binbin', 'bin11', '현민', '010-2345-7891', 
	'서울시 강남구 도산대로101길 30, 925빌딩 4층', DEFAULT, DEFAULT);
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 'songriver', 'river1', '손강', '010-5252-2525', 
	'서울시 강남구 언주로150길 34, 삼경빌딩 5층', DEFAULT, DEFAULT);

SELECT * FROM TB_USER;

COMMIT;

----------------------------------
-- 주문 내역 테이블 생성
-- (회원번호)/주문번호/주문날짜/상품명/옵션/수량/가격/배송상태/(취소여부(N))

CREATE TABLE TB_ORDER(
	USER_NO NUMBER CONSTRAINT USER_NO_FK REFERENCES TB_USER(USER_NO),
	ORDER_NO NUMBER CONSTRAINT ORDER_NO_PK PRIMARY KEY,
	ORDER_DATE DATE,
	PRODUCT_NAME VARCHAR2(30) NOT NULL,
	PRODUCT_OP VARCHAR2(20) NOT NULL,
	PRODUCT_QU NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	SHIPPING VARCHAR2(20) NOT NULL,
	WITHDRAW CHAR(1) DEFAULT 'N' CHECK(WITHDRAW IN ('Y', 'N'))
);

SELECT * FROM TB_ORDER;

COMMENT ON COLUMN TB_ORDER.USER_NO IS '주문한 회원 번호';
COMMENT ON COLUMN TB_ORDER.ORDER_NO IS '주문 번호';
COMMENT ON COLUMN TB_ORDER.ORDER_DATE IS '주문 날짜';
COMMENT ON COLUMN TB_ORDER.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN TB_ORDER.PRODUCT_OP IS '상품 옵션';
COMMENT ON COLUMN TB_ORDER.PRODUCT_QU IS '주문 수량';
COMMENT ON COLUMN TB_ORDER.PRICE IS '주문 금액';
COMMENT ON COLUMN TB_ORDER.SHIPPING IS '배송 상태';
COMMENT ON COLUMN TB_ORDER.WITHDRAW IS '주문 취소 여부';

-- 주문 번호 시퀀스
CREATE SEQUENCE SEQ_ORDER_NO
-- 날짜+넘버링
