-- SYS 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 사용자 계정 생성
CREATE USER project1_hjh IDENTIFIED BY hjh1234;

-- 생성한 사용자 계정에 권한 부여
GRANT RESOURCE, CONNECT TO project1_hjh;

-- 테이블 스페이스 할당
ALTER USER project1_hjh DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;

-----------------------------------------

-- project1_hjh 계정
-- 회원 정보 테이블 생성
-- (회원번호)/아이디/비밀번호/이름/전화번호/주소/가입날짜(SYSDATE)/(탈퇴여부(N))

CREATE TABLE TB_USER(
	USER_NO NUMBER CONSTRAINT USER_NO_PK PRIMARY KEY,
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR2(30),
	USER_PHONE VARCHAR2(30),
	USER_ADDR VARCHAR2(70) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y', 'N')),
	CONSTRAINT USER_ID_NAME_PHONE_U UNIQUE(USER_ID, USER_NAME, USER_PHONE)
);

SELECT * FROM TB_USER;

-- SEQUENCE